---
kind: pipeline
type: docker
name: test

steps:
  - name: testing
    image: alpine
    commands: 
      - echo "oi"
trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: production

steps:
  - name: sending_to_prod
    image: alpine
    commands:
      - echo "DEPLOY TO PRODUCTION"

trigger:
  event:
    - promote
    - push
    - pull_request
  branches:
    - production
  target:
    - production
 

