---
kind: pipeline
type: test
name: test

steps:
   - name: tests
     image: node:latest
     commands: 
     - npm install
   
   - name: say_hi
     commands: 
     - echo oi
---
kind: pipeline
type: deployment
name: deploy

steps:
    - name: say_hi
      commands:
      - echo "DEPLOY TO PRODUCTION"

trigger:
    event:
    - promote
    targe:
    - production

 

