---
kind: pipeline
type: test
name: test

steps:
  - name: say_hi
    commands: 
      - echo oi
trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: deployment
name: production

steps:
  - name: say_hi
    commands:
      - echo "DEPLOY TO PRODUCTION"

trigger:
  event:
    - promote
  branches:
    - production
  target:
    - production
 

