pipeline:
  build:
    image: node:latest
    commands: npm install
  aurelio:
    image: node:latest
    commands: echo "OI mundo"
    when:
      event:
      - promote
      target:
      - production
    
