pipeline:
  build:
    image: node:latest
    commands: npm install
  production:
    image: node:latest
    commands: echo "OI prod"
    when:
      branch:
      - production
      event:
      - promote
      target:
      - production
  staging:
    image: node:latest
    commands: echo "OI staging"
    when:
      event:
      - promote
      target:
      - staging    
 

